const mongoose=require("mongoose")
const resumeSchema=new mongoose.Schema(
    {
   userId:{
      type:mongoose.Schema.Types.ObjectId,
      ref:"User",
      required:true
    },
    personalInfo:{
     firstname:String,
     lastname:String,
     phone:String,
     email:String,
     address:String,
     linkedin:String,
     github:String
    },
    education:[
        {
            degree:String,
            institution:String,
            startYear:Date,
            endDate:Date
        }
    ],
    experience:[
        {
            company:String,
            role:String,
            startDate:Date,
            endDate:{
               type:Date,
               default:null
            },
            description:String
        }
    ],
    skill:[String],
    projects:[
        {
            title:String,
            description:String,
            techStack:[String]
        }
    ]
},{timestamps:true})
